# Generated by Django 5.1.3 on 2025-01-16 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='women',
            new_name='test_time_cr_fd4e1e_idx',
            old_name='women_time_cr_455053_idx',
        ),
        migrations.AlterModelTable(
            name='women',
            table='test',
        ),
    ]
