# Generated by Django 5.1.3 on 2025-01-16 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_rename_women_time_cr_455053_idx_test_time_cr_fd4e1e_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='women',
            new_name='women_time_cr_455053_idx',
            old_name='test_time_cr_fd4e1e_idx',
        ),
        migrations.AlterModelTable(
            name='women',
            table='women',
        ),
    ]
