# Generated by Django 5.1.3 on 2024-12-01 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0009_husband_m_count'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='women',
            new_name='women_time_cr_455053_idx',
            old_name='women_women_time_cr_9f33c2_idx',
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='husband',
            table='husband',
        ),
        migrations.AlterModelTable(
            name='tagpost',
            table='tag_post',
        ),
        migrations.AlterModelTable(
            name='women',
            table='women',
        ),
    ]
