# Generated by Django 5.1.3 on 2024-12-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0012_uploadedfile_alter_women_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
