# Generated by Django 5.1.3 on 2024-12-15 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0013_women_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
